# Generated by Django 4.2.16 on 2024-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user1', max_length=255, unique=True)),
                ('password', models.CharField(default='password123', max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
